### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by Pisich** [Marcox385/Snake.py#1]
Since GitHub promotes Open Source, why would you post a program without its source code? Please add the code to it.
Thank you @Marcox385

**Comment by Pisich** [comment]
Any update?

**Comment by Marcox385** [comment]
Sorry @Pisich, currently, I'm working on an automatic missile launcher that detects my enemies, I suggest that you desist on any further petitions on this code if you want to keep breathing. Greetings!

**Comment by Marcox385** [comment]
The code has been uploaded, you can check it out right now. Greetings.

**Comment by Pisich** [comment]
Thank you Marcox

**Comment by Marcox385** [comment]
No problem.

**Comment by Pisich** [comment]
You should have left the executable file as a release of your project

**Comment by Marcox385** [comment]
A good programmer will know how to do that, if you're one then you don't have to worry. Greetings!!!!
